### PR TITLE
add TableBox - a simple table w/ header

### PR DESCRIPTION
**Pull request by ba0f3**

### CODE REVIEW

**Comment by enthus1ast** [comment]
nice! can you also add this to the demo.nim? :)

**Comment by ba0f3** [comment]
there is an example in test folder already, but I can add it to demo too

**Comment by enthus1ast** [comment]
> there is an example in test folder already, but I can add it to demo too

yes that would be nice, this way one can see all the features in one place

**Comment by ba0f3** [comment]
I rebased all commits into single one

**Pull request merged**
